version: "3"

services:
  clightning_bitcoin:
    image: nicolasdorier/clightning
    container_name: btcpayserver_clightning_bitcoin
    restart: always
    environment:
      LIGHTNINGD_OPT: |
        bitcoin-datadir=/etc/bitcoin
        bitcoin-rpcconnect=bitcoind
        ipaddr=${BTCPAY_HOST}
        network=${NBITCOIN_NETWORK:-regtest}
        alias=${LIGHTNING_ALIAS}
        chain=btc
    volumes:
      - "clightning_bitcoin_datadir:/root/.lightning"
      - "bitcoin_datadir:/etc/bitcoin"
    ports:
      - "9735:9735"
    links:
      - bitcoind
  btcpayserver:
    environment:
      BTCPAY_BTCLIGHTNING: "/etc/clightning_bitcoin/lightning-rpc"
    volumes:
      - "clightning_bitcoin_datadir:/etc/clightning_bitcoin"
    links:
      - clightning_bitcoin
volumes:
  clightning_bitcoin_datadir: