version: "3"

services:
  clightning_bitcoin:
    image: nicolasdorier/clightning:v0.6.2-3
    stop_signal: SIGKILL
    container_name: btcpayserver_clightning_bitcoin
    restart: unless-stopped
    environment:
      LIGHTNINGD_NETWORK: ${NBITCOIN_NETWORK:-regtest}
      LIGHTNINGD_CHAIN: btc
      LIGHTNINGD_EXPLORERURL: "http://nbxplorer:32838/"
      LIGHTNINGD_OPT: |
        bitcoin-datadir=/etc/bitcoin
        bitcoin-rpcconnect=bitcoind
        announce-addr=${BTCPAY_HOST}:9735
        bind-addr=0.0.0.0:9735
        network=${NBITCOIN_NETWORK:-regtest}
        alias=${LIGHTNING_ALIAS}
        chain=btc
    volumes:
      - "clightning_bitcoin_datadir:/root/.lightning"
      - "bitcoin_datadir:/etc/bitcoin"
      - "nbxplorer_datadir:/root/.nbxplorer"
    ports:
      - "9735:9735"
    links:
      - nbxplorer
      - bitcoind
  clightning_bitcoin_spark:
    image: shesek/spark-wallet:0.2.0-WIP
    stop_signal: SIGKILL
    restart: unless-stopped
    environment:
      NETWORK: ${NBITCOIN_NETWORK:-regtest}
      SPARK_OPT: --no-tls -C /data/.cookie
    volumes:
      - "clightning_bitcoin_datadir:/etc/lightning"
      - "clightning_bitcoin_spark:/data"
    links:
      - clightning_bitcoin
    expose:
     - "9737"
  btcpayserver:
    environment:
      BTCPAY_BTCLIGHTNING: "type=clightning;server=unix://etc/clightning_bitcoin/lightning-rpc"
      BTCPAY_BTCEXTERNALSPARK: "server=${BTCPAY_PROTOCOL:-https}://${BTCPAY_HOST}${BTCPAY_ROOTPATH:-/}spark/btc;cookiefile=/etc/clightning_bitcoin_spark/.cookie"
    volumes:
      - "clightning_bitcoin_datadir:/etc/clightning_bitcoin"
      - "clightning_bitcoin_spark:/etc/clightning_bitcoin_spark"
    links:
      - clightning_bitcoin
volumes:
  clightning_bitcoin_datadir:
  clightning_bitcoin_spark: