version: "3"

services:
  bitcoind:
      restart: unless-stopped
      container_name: btcpayserver_bitcoind
      image: btcpayserver/bitcoin:0.18.0
      environment:
        BITCOIN_NETWORK: ${NBITCOIN_NETWORK:-regtest}
        BITCOIN_EXTRA_ARGS: |
          rpcport=43782
          rpcbind=0.0.0.0:43782
          port=39388
          disablewallet=1
          whitelist=0.0.0.0/0
          # rpcuser=lnd
          # rpcpassword=afixedpasswordbecauselndsuckswithcookiefile
          # We need to use rpcauth because we also need cookieauth. rpcpassword disabled cookie file auth.
          # Be careful if you copy the line below from the docker-compose.yml! A dollar sign is escaped
          rpcauth=lnd:d031f7567c5b02ba95524170e51c77f4$$827ce5412f653d6613c2f480e521eb437c866b999bdeb2ee4f9c41d3b00dff1c
      expose:
        - "43782"
        - "39388"
      volumes:
        - "bitcoin_datadir:/data"
  nbxplorer:
      environment:
        NBXPLORER_CHAINS: "btc"
        NBXPLORER_BTCRPCURL: http://bitcoind:43782/
        NBXPLORER_BTCNODEENDPOINT: bitcoind:39388
      volumes:
        - "bitcoin_datadir:/root/.bitcoin"
  btcpayserver:
      environment:
        BTCPAY_CHAINS: "btc"
        BTCPAY_BTCEXPLORERURL: http://nbxplorer:32838/
volumes:
  bitcoin_datadir: