version: "3"

services:

  btcpayserver:
    image: junglelab/btcpayjungle:1.0.1.63
    ports:
      - 8080:49392
    expose:
      - "49392"
    environment:
      BTCPAY_POSTGRES: "User ID=postgres;Host=postgres;Port=5432;Database=btcpayserver"
      BTCPAY_NETWORK: regtest
      BTCPAY_EXPLORERURL: http://nbxplorer:32838/
      BTCPAY_BIND: 0.0.0.0:49392
    links:
      - nbxplorer
      - postgres

  nbxplorer:
    image: nicolasdorier/nbxplorer:1.0.1.23
    expose:
      - "32838"
    environment:
      NBXPLORER_NETWORK: regtest
      NBXPLORER_RPCURL: http://bitcoind:43782/
      NBXPLORER_RPCUSER: ceiwHEbqWI83
      NBXPLORER_RPCPASSWORD: DwubwWsoo3
      NBXPLORER_NODEENDPOINT: bitcoind:8332
      NBXPLORER_BIND: 0.0.0.0:32838
      NBXPLORER_NOAUTH: 1
    links:
      - bitcoind

  bitcoind:
    container_name: btcpayserver_regtest_bitcoind
    image: nicolasdorier/docker-bitcoin:0.16.0
    environment:
      BITCOIN_EXTRA_ARGS: "rpcuser=ceiwHEbqWI83\nrpcpassword=DwubwWsoo3\nregtest=1\nrpcport=43782\nport=8332"
    expose:
      - "43782"
      - "8332"

  postgres:
    image:  postgres:9.6.5
